import { Inter } from 'next/font/google'
import './globals.css'
import TailHeaderMenu from './comm/TailHeaderMenu'
import TailFooter from './comm/TailFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App K-digital',
  description: 'K-digital Project : Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center h-screen w-full max-w-screen-xl mx-auto">
        <TailHeaderMenu />
        <main className='grow flex flex-col justify-center items-center'>
          {children}
        </main>
        <TailFooter />
      </body>
    </html>
  )
}
